// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAODMP3NF1q5WSDND5qaCO7cAN8WMoJ1X0',
    appId: '1:60470626448:web:7408fdc6ab1e934863b015',
    messagingSenderId: '60470626448',
    projectId: 'provaandreabastecimento',
    authDomain: 'provaandreabastecimento.firebaseapp.com',
    storageBucket: 'provaandreabastecimento.firebasestorage.app',
    measurementId: 'G-NJT5CFBWXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLXUnZHLkRY1yZdIrwQpSCXUF7djc9uYQ',
    appId: '1:60470626448:android:94921aa416c5958063b015',
    messagingSenderId: '60470626448',
    projectId: 'provaandreabastecimento',
    storageBucket: 'provaandreabastecimento.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_kUb54N8kgOO6s5Pp9l4z4EjQxwqrFCs',
    appId: '1:60470626448:ios:dc83f9b0c63fe4e963b015',
    messagingSenderId: '60470626448',
    projectId: 'provaandreabastecimento',
    storageBucket: 'provaandreabastecimento.firebasestorage.app',
    iosBundleId: 'com.example.provaandreabastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_kUb54N8kgOO6s5Pp9l4z4EjQxwqrFCs',
    appId: '1:60470626448:ios:dc83f9b0c63fe4e963b015',
    messagingSenderId: '60470626448',
    projectId: 'provaandreabastecimento',
    storageBucket: 'provaandreabastecimento.firebasestorage.app',
    iosBundleId: 'com.example.provaandreabastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAODMP3NF1q5WSDND5qaCO7cAN8WMoJ1X0',
    appId: '1:60470626448:web:b83b5b3d144e964f63b015',
    messagingSenderId: '60470626448',
    projectId: 'provaandreabastecimento',
    authDomain: 'provaandreabastecimento.firebaseapp.com',
    storageBucket: 'provaandreabastecimento.firebasestorage.app',
    measurementId: 'G-6MLJLGMKP4',
  );
}
